# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: GTPvulnerabilitiesEnablement
# label used for menu selection
label: Initialize All GTP vulnerabilities
description: Enable and initialize all GTP vulnerabilities

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - GTP flood protection initialization

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: initialGTPnoAttributes
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/vulnerability/entry[@name='alert-vulnerability']/threat-exception
    file: initializeAndEnableGTP.xml
  - name: initialGTPwithAttributes
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/vulnerability/entry[@name='alert-vulnerability']/threat-exception
    file: initializeAndEnableGTPwithAttributes.xml


# ---------------------------------------------------------------------
# end of snippets section
