# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: GTPfloodConfigurableSkillet
# label used for menu selection
label: Adjusting GTP Flood Attributes
description: This skillet helps you to adjust GTP Flood Attributes

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - GTP Flood Protection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: 40065_interval
    description: time interval value for GTPv2-C Modify Bearer Request Flood
    default: 2
    type_hint: text
  - name: 40065_threshold
    description: threshold value for GTPv2-C Modify Bearer Request Flood
    default: 255
    type_hint: text
  - name: 40065_src_dst
    description: which flow direction to use to track GTPv2-C Modify Bearer Request Flood
    default: source-and-destination
    type_hint: text

  - name: 40054_interval
    description: time interval value for GTPv1-C Create PDP Context Request Flood
    default: 1
    type_hint: text
  - name: 40054_threshold
    description: threshold value for GTPv1-C Create PDP Context Request Flood
    default: 1000
    type_hint: text
  - name: 40054_src_dst
    description: which flow direction to use to track GTPv1-C Create PDP Context Request Flood
    default: source-and-destination
    type_hint: text

  - name: 40055_interval
    description: time interval value for GTPv1-C Update PDP Context Request Flood
    default: 1
    type_hint: text
  - name: 40055_threshold
    description: threshold value for GTPv1-C Update PDP Context Request Flood
    default: 1000
    type_hint: text
  - name: 40055_src_dst
    description: which flow direction to use to track GTPv1-C Update PDP Context Request Flood
    default: source-and-destination
    type_hint: text

  - name: 40063_interval
    description: time interval value for GTPv2-C Create Session Request Flood
    default: 2
    type_hint: text
  - name: 40063_threshold
    description: threshold value for GTPv2-C Create Session Request Flood
    default: 255
    type_hint: text
  - name: 40063_src_dst
    description: which flow direction to use to track GTPv2-C Create Session Request Flood
    default: source-and-destination
    type_hint: text

  - name: 40067_interval
    description: time interval value for GTPv2-C Echo Request Flood
    default: 2
    type_hint: text
  - name: 40067_threshold
    description: threshold value for GTPv2-C Echo Request Flood
    default: 255
    type_hint: text
  - name: 40067_src_dst
    description: which flow direction to use to track GTPv2-C Echo Request Flood
    default: source-and-destination
    type_hint: text

  - name: 40064_interval
    description: time interval value for GTPv2-C Delete Session Request Flood
    default: 2
    type_hint: text
  - name: 40064_threshold
    description: threshold value for GTPv2-C Delete Session Request Flood
    default: 255
    type_hint: text
  - name: 40064_src_dst
    description: which flow direction to use to track GTPv2-C Delete Session Request Flood
    default: source-and-destination
    type_hint: text

  - name: 40066_interval
    description: time interval value for GTPv2-C Release Access Bearer Request Flood
    default: 2
    type_hint: text
  - name: 40066_threshold
    description: threshold value for GTPv2-C Release Access Bearer Request Flood
    default: 255
    type_hint: text
  - name: 40066_src_dst
    description: which flow direction to use to track GTPv2-C Release Access Bearer Request Flood
    default: source-and-destination
    type_hint: text


  - name: 40056_interval
    description: time interval value for GTPv1-C Delete PDP Context Request Flood
    default: 2
    type_hint: text
  - name: 40056_threshold
    description: threshold value for GTPv1-C Delete PDP Context Request Flood
    default: 255
    type_hint: text
  - name: 40056_src_dst
    description: which flow direction to use to track GTPv1-C Delete PDP Context Request Flood
    default: source-and-destination
    type_hint: text

  - name: 40057_interval
    description: time interval value for GTPv1-C Echo Request Flood
    default: 2
    type_hint: text
  - name: 40057_threshold
    description: threshold value for GTPv1-C Echo Request Flood
    default: 255
    type_hint: text
  - name: 40057_src_dst
    description: which flow direction to use to track GTPv1-C Echo Request Flood
    default: source-and-destination
    type_hint: text

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: GTPvaluesToAdjust
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/vulnerability/entry[@name='alert-vulnerability']/threat-exception
    file: adjustThresholdsGTP.xml


# ---------------------------------------------------------------------
# end of snippets section
